apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: factory
resources:
- manifests.yaml
images:
- name: ghcr.io/olafkfreund/odin
  newName: ghcr.io/olafkfreund/odin
  newTag: sha-ae82ada
