apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: factory
resources:
- manifests.yaml
images:
- name: ghcr.io/olafkfreund/tfactory
  newName: ghcr.io/olafkfreund/tfactory
  newTag: sha-256ba8b
