apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: factory
resources:
- manifests.yaml
images:
- name: ghcr.io/olafkfreund/cfactory
  newName: ghcr.io/olafkfreund/cfactory
  newTag: sha-f047d7c
- name: ghcr.io/olafkfreund/cfactory-frontend
  newName: ghcr.io/olafkfreund/cfactory-frontend
  newTag: sha-f047d7c
