apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: factory
resources:
- manifests.yaml
images:
- name: public.ecr.aws/zinclabs/openobserve
  newName: public.ecr.aws/zinclabs/openobserve
  newTag: v0.90.3
